# Generated by Django 3.2.3 on 2021-06-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
