# Generated by Django 3.2.3 on 2021-06-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_up',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
