# Generated by Django 3.0.5 on 2021-06-30 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210630_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='id_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
    ]
