# Generated by Django 3.0.5 on 2021-06-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210630_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='id_order',
            new_name='order',
        ),
    ]
